title: Jack Lawrence # your name (or website title) here
logo: "profilePanda.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Student in oceanography (physical) <br>

  Graduate School of Oceanography <br>

  <a href="http://bit.ly/tjlawrence">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
